# Generated by Django 5.1.6 on 2025-02-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата оплаты"),
        ),
    ]
