# Generated by Django 5.1.6 on 2025-03-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="mailings",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
