services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  
  db:
    image: postgres:16.0
    volumes:
      - postgers_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
  
  celery:
    build: .
    command: poetry run celery -A config worker -l INFO -P eventlet
    env_file:
      - .env
    depends_on:
      - db
      - redis
    
  celery-beat:
    build: .
    command: poetry run celery -A config beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis


volumes:
  postgers_data:
  static_volume: